/**
 * @fileoverview gRPC-Web generated client stub for proving_network
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: proving_network.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as proving_network_pb from './proving_network_pb'; // proto import: "proving_network.proto"


export class ProvingNetworkClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorProveTask = new grpcWeb.MethodDescriptor(
    '/proving_network.ProvingNetwork/ProveTask',
    grpcWeb.MethodType.UNARY,
    proving_network_pb.ProveTaskRequest,
    proving_network_pb.ProveTaskResponse,
    (request: proving_network_pb.ProveTaskRequest) => {
      return request.serializeBinary();
    },
    proving_network_pb.ProveTaskResponse.deserializeBinary
  );

  proveTask(
    request: proving_network_pb.ProveTaskRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proving_network_pb.ProveTaskResponse>;

  proveTask(
    request: proving_network_pb.ProveTaskRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proving_network_pb.ProveTaskResponse) => void): grpcWeb.ClientReadableStream<proving_network_pb.ProveTaskResponse>;

  proveTask(
    request: proving_network_pb.ProveTaskRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proving_network_pb.ProveTaskResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/proving_network.ProvingNetwork/ProveTask',
        request,
        metadata || {},
        this.methodDescriptorProveTask,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/proving_network.ProvingNetwork/ProveTask',
    request,
    metadata || {},
    this.methodDescriptorProveTask);
  }

}

